clean k8s manifest output
volvo-cars/lingon pull request #71
Opened 2023-04-23 08:41 UTC by veggiemonk

* adding more tests
* using sjson to remove unused fields (status, ...)
* adding more test utility functions
fixes #70

2023-04-23 11:12 UTC, LeonardAukea requested changes
I think it makes sense to also remove the additional `metadata.generation`, `metadata.uid`, `metadata.resourceVersion` before merge. 

This also makes me think if we should provide a "neat" option already at import. i.e Why do we need this? 

```go
	Status: appsv1.DeploymentStatus{
		AvailableReplicas: int32(1),
		Conditions: []appsv1.DeploymentCondition{appsv1.DeploymentCondition{
			LastTransitionTime: metav1.Time{Time: time.Time{}},
			LastUpdateTime:     metav1.Time{Time: time.Time{}},
			Message:            "ReplicaSet \"vault-agent-injector-d54f65ddd\" has successfully progressed.",
			Reason:             "NewReplicaSetAvailable",
			Status:             corev1.ConditionStatus("True"),
			Type:               appsv1.DeploymentConditionType("Progressing"),
		}, appsv1.DeploymentCondition{
			LastTransitionTime: metav1.Time{Time: time.Time{}},
			LastUpdateTime:     metav1.Time{Time: time.Time{}},
			Message:            "Deployment has minimum availability.",
			Reason:             "MinimumReplicasAvailable",
			Status:             corev1.ConditionStatus("True"),
			Type:               appsv1.DeploymentConditionType("Available"),
		}},
		ObservedGeneration: int64(3),
		ReadyReplicas:      int32(1),
		Replicas:           int32(1),
		UpdatedReplicas:    int32(1),
	},

```

2023-04-24 06:16 UTC, LeonardAukea commented
> I think it makes sense to also remove the additional `metadata.generation`, `metadata.uid`, `metadata.resourceVersion` before merge.
> 
> This also makes me think if we should provide a "neat" option already at import. i.e Why do we need this?
> 
> ```go
> 	Status: appsv1.DeploymentStatus{
> 		AvailableReplicas: int32(1),
> 		Conditions: []appsv1.DeploymentCondition{appsv1.DeploymentCondition{
> 			LastTransitionTime: metav1.Time{Time: time.Time{}},
> 			LastUpdateTime:     metav1.Time{Time: time.Time{}},
> 			Message:            "ReplicaSet \"vault-agent-injector-d54f65ddd\" has successfully progressed.",
> 			Reason:             "NewReplicaSetAvailable",
> 			Status:             corev1.ConditionStatus("True"),
> 			Type:               appsv1.DeploymentConditionType("Progressing"),
> 		}, appsv1.DeploymentCondition{
> 			LastTransitionTime: metav1.Time{Time: time.Time{}},
> 			LastUpdateTime:     metav1.Time{Time: time.Time{}},
> 			Message:            "Deployment has minimum availability.",
> 			Reason:             "MinimumReplicasAvailable",
> 			Status:             corev1.ConditionStatus("True"),
> 			Type:               appsv1.DeploymentConditionType("Available"),
> 		}},
> 		ObservedGeneration: int64(3),
> 		ReadyReplicas:      int32(1),
> 		Replicas:           int32(1),
> 		UpdatedReplicas:    int32(1),
> 	},
> ```

I thought about it a bit more. no need to waste time on this. The user can just as well run `kubectl-neat` or remove fields from the struct whilst in go. That said, I think the output should be neat and reflect the struct.

2023-04-24 10:11 UTC, LeonardAukea commented on pkg/kube/importoption.go
> +	GroupByKind:    false, // TODO: should default to true ?
What is the argument for not having this as default?

2023-04-24 11:54 UTC, veggiemonk commented on pkg/kube/importoption.go
> +	GroupByKind:    false, // TODO: should default to true ?
Because it is more a opt-in thing 🤷‍♂️ I have no arguments really. 
I always turn it on.
Maybe I should change it to true by default ? 
@LeonardAukea what do you think ?

2023-04-24 12:06 UTC, LeonardAukea commented on pkg/kube/importoption.go
> +	GroupByKind:    false, // TODO: should default to true ?
If you always turn it on then maybe it makes sense to have it more like and opt-out thing :) Easy to change back later if users happen to complain.

2023-04-24 14:28 UTC, LeonardAukea approved these changes
:rocket: Nice one!

2023-04-25 08:12 UTC, merged